### ISSUE TITLE
historical splits api return empty list

### ISSUE THREAD

**Issue by Sinansi** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#11]
I installed eodhd version 1.0.13 to work on the new get_historical_splits_data api, but it returns an empty list when I use the following command:

resp = api.get_historical_splits_data("AAPL.US", "2000-01-01", "2023-05-01")

I thought it is a connection issue, but then I checked the code and found that the dates are switched around. The date_to comes before the date_from. So I reversed the dates as follows and it worked:

resp = api.get_historical_splits_data("AAPL.US", "2023-05-01", "2000-01-01")

The same issues occurs for get_historical_dividends_data.

**Comment by deios0** [comment]
Hello, thank you for the report, we will check what we can do here.
