### ISSUE TITLE
intraday query must contain time stamp

### ISSUE THREAD

**Issue by Sinansi** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#12]
It says on your website that the 5 minutes interval history go back to October 2020.

I want 5 minutes data of January 2023 for Apple, so I used the following query:

resp = api.get_historical_data("AAPL.US", "5m", "2023-01-01", "2023-01-31")

I got a dataframe containing the 5 minutes data of today and yesterday only.

After many attempts (wasting an hour), I noticed that if you dont include the time stamp in an intraday query, the query will still execute without any problem, but produce the wrong results.

The following query returned the desired results:
resp = api.get_historical_data("AAPL.US", "5m", "2023-03-01 00:00:01", "2023-03-31 23:59:59")

Please, raise an error when an intraday query contains a date without a time stamp.

Thank you!

**Comment by deios0** [comment]
Hello, according to our documentation (https://eodhistoricaldata.com/financial-apis/intraday-historical-data-api/) all timestamps for intraday data should be UNIX timestamps (like this: https://www.unixtimestamp.com/).

**Comment by Sinansi** [comment]
I think this library does not support unix time stamp.

When I use unix time stamp, it is exactly like using normal date but without time stamp. 
The query get executed but with undesired results.

The following query uses unix time stamp to retrieve 5 minutes data of Apple for January 2023.

resp = api.get_historical_data("AAPL.US", '5m', range_start='1672520400', range_end='1675112400')

It returns data for today and yesterday only. I believe this is the default 5 minutes history when the range dates are ignored.

The following query returns the desired results and it uses normal date format:

resp = api.get_historical_data("AAPL.US", "5m", "2023-01-01 00:00:01", "2023-01-31 23:59:59")

Anyhow, I will just use the one that is working.

Thank you!

**Comment by deios0** [comment]
Thank you, we will check it.
