### ISSUE TITLE
Add ability to get delisted symbols?

### ISSUE THREAD

**Issue by ddm-j** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#16]
The method `get_exchange_symbols` does not support the request argument `delisted=1`. Consider adding? Not sure which other keyword arguments are not supported across this API.

**Comment by Nawado** [comment]
Hello. Try to use this function: get_list_of_tickers
You can find documentation about this func:
```
from eodhd import APIClient
#add your token here
api = APIClient('demo')
help(api.get_list_of_tickers)
