### ISSUE TITLE
sharing python code to download full 1 minute history

### ISSUE THREAD

**Issue by Sinansi** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#22]
The most challenging thing I had from using this library, is downloading the full 1 minute history. I kept breaching the 120 day limit, which triggers an exception. Additionally, calling an end date that falls out of the month also triggers an exception.

After trial and error, I think the following code is a good example to download the full 1 minute history without triggering exceptions. So I just wanted to share it.

def createOneMinHistory(symbol):
    sym = symbol + "." + "US"
    df = pd.DataFrame()
    for i in range(2004, 2023):
        print('downloading data of ' + sym + ' for year ' + str(i))
        df1 = api.get_historical_data(sym, "1m", str(i) + "-01-01 00:00:01", str(i) + "-03-31 23:59:59")
        df2 = api.get_historical_data(sym, "1m", str(i) + "-04-01 00:00:01", str(i) + "-06-30 23:59:59")
        df3 = api.get_historical_data(sym, "1m", str(i) + "-07-01 00:00:01", str(i) + "-09-30 23:59:59")
        df4 = api.get_historical_data(sym, "1m", str(i) + "-10-01 00:00:01", str(i) + "-12-31 23:59:59")
        df = pd.concat([df, df1, df2, df3, df4], axis=0)
    return df

**Comment by whittlem** [comment]
I raised a PR in v1.0.21 which fixes this. For some reason the "eodhd" library has not updated in PyPi. I've raised an Issue for them push it again.

To retrieve the minutes you can do this in v1.0.21:

  df_minutes = api.get_historical_data(symbol="HSPX.LSE", interval="1m", iso8601_start="2023-09-01", iso8601_end="2023-09-08")
  print(df_minutes)

**Comment by Sinansi** [comment]
I wish to retrieve the full 1 minute history of a stock. For example I wish to retrieve the 1 minute data of Microsoft from January 2004 to January 2023. This command cannot be done in one line because you are going to trigger maximum limit. You can only download 120 days of 1 minute data. If you exceed 120 days, you trigger an exception handling that will shutdown the python console. That's why I created the above loop. 

[](https://eodhistoricaldata.com/api/intraday/AAPL.US?api_token=60070a6b6b6988.16973783)

**Comment by whittlem** [comment]
120 days of 1 minute data is a huge amount of data, worst case 172800 candles. I'm not entirely sure EODHD will allow you to pull this in one go. They have the highest limits I've seen on my data provider but I think this even for them would be a lot. What you will need to do is create some code to iterate through batches and concatenate them. 

I've done this before in my PyCryptoBot app, but you can use this as an example to see how it can be done...

    def getHistoricalDataChained(
        market: str = "BTC-GBP", granularity: int = 3600, max_interations: int = 1
    ) -> pd.DataFrame:
        df1 = getHistoricalData(market, granularity)

        # print(f"end: {df1['date'].max()}")
        # print(f"start: {df1['date'].min()}")
        # print("-")

        if max_interations == 1:
            return df1

        def getPreviousDateRange(df: pd.DataFrame = None) -> tuple:
            end_date = df["date"].min() - timedelta(seconds=granularity)
            new_start = end_date - timedelta(seconds=granularity * 300)

            # rint(f"end: {end_date}")
            # print(f"start: {new_start}")
            # print("-")

            return (str(new_start).replace(" ", "T"), str(end_date).replace(" ", "T"))

        iteration = 0
        result_df = pd.DataFrame()
        while iteration < (max_interations - 1):
            start_date, end_date = getPreviousDateRange(df1)
            df2 = getHistoricalData(market, granularity, start_date, end_date)
            result_df = pd.concat([df2, df1]).drop_duplicates()
            df1 = result_df
            iteration = iteration + 1

        if "date" in result_df:
            result_df.sort_values(by=["date"], ascending=True, inplace=True)

            return result_df
            
    df = getHistoricalDataChained("BTC-GBP", 3600, 3)

**Comment by Sinansi** [comment]
Thank you so much!
