### ISSUE TITLE
splitadjusted parameter is missing 

### ISSUE THREAD

**Issue by Sinansi** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#23]
The End-Of-Day Historical Stock Market Data API ( api.get_historical_data) does not provide split adjusted close price. 

So I use the Technical Indicator API (api.get_technical_indicator_data) for downloading split adjusted close price.

When I download adjusted close price from the technical indicator API, I set the function parameter to function="splitadjusted".

Now I installed eodhd version 1.0.18, but the "splitadjusted" parameter is no longer available. 
Using "splitadjusted" raises an error ValueError.

It says in the documentation, you can only use the following values for the function parameter:

['avgvol', 'avgvolccy', 'sma', 'ema', 'wma', 'volatility', 'stochastic', 'rsi', 'stddev', 'stochrsi', 'slope', 'dmi', 'adx', 'macd', 'atr', 'cci', 'sar', 'bbands', 'format_amibroker']

Do you have another method for downloading split adjusted close price?

P.S: I am not interested in technical indicators.

**Comment by Nawado** [comment]
Hi. Try to use 1.0.19 version with splitadjusted value.

**Comment by Sinansi** [comment]
I have installed 1.0.19 and I successfully downloaded adjusted close prices from the technical indicator API.

Please note that the documentation of 1.0.19 does not state that the value of the function parameter can be "splitadjusted".

The following list in the documentation does not include "splitadjusted"

All possible values for function parameter: 
                                        ['avgvol', 'avgvolccy', 'sma', 'ema', 'wma', 'volatility', 'stochastic',
                                        'rsi', 'stddev', 'stochrsi', 'slope', 'dmi', 'adx', 'macd', 'atr',
                                        'cci', 'sar', 'bbands', 'format_amibroker']

**Comment by Sinansi** [comment]
Just a side note. Today I literally spent hours installing and uninstalling eodhd package. This delay is due to issues caused by Matplotlib. If you can remove Matplotlib library from the dependencies, it would help alot. Or perhaps use matplotlib-base to reduce the burden.

**Comment by Nawado** [comment]
Ok! We will check Matplotlib dependency and try to fix it. 
Documentation will be updated

**Comment by Sinansi** [comment]
Thank you so much!
