### ISSUE TITLE
Unable to raise a PR for a new branch called v1.0.21

### ISSUE THREAD

**Issue by whittlem** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#31]
eodhd % git push --set-upstream origin v1.0.21
remote: Permission to EodHistoricalData/EODHD-APIs-Python-Financial-Library.git denied to whittlem.
fatal: unable to access 'https://github.com/EodHistoricalData/EODHD-APIs-Python-Financial-Library/': The requested URL returned error: 403

**Comment by Nawado** [comment]
This is strange since the repository is public. I gave you a role to record. Previously, users created their own pull requests and there were no problems with access

**Comment by whittlem** [comment]
It's worked now. Thanks

**Comment by whittlem** [comment]
I've raised a PR from my v1.0.21 branch to main. Do you want to review it before merging?

**Comment by whittlem** [comment]
If you are happy with it, please can you merge it and push the update to PyPI.

**Comment by Nawado** [comment]
Ok, I'll take a look at the changes tonight and merge them if everything goes well.

**Comment by whittlem** [comment]
Thanks
