### ISSUE TITLE
Can you please push the main branch to PyPi?

### ISSUE THREAD

**Issue by whittlem** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#33]
The library image published to PyPi is not the latest version. Can you please push the main branch to PyPi?

Thanks,
Mike

**Comment by whittlem** [comment]
@Nawado, any luck with this?

**Comment by whittlem** [comment]
@Nawado, I've fixed this in v1.0.22. The dependency libraries needed to be upgraded to worth with Python 3.11. I've done this now. Can you push this to PyPi please? Thanks

**Comment by Nawado** [comment]
Hello!
Its done.

**Comment by whittlem** [comment]
It's working, thanks.
