### ISSUE TITLE
Discrepancy between description and default behaviour in the API client

### ISSUE THREAD

**Issue by Comitica** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#48]
The [comment](https://github.com/EodHistoricalData/EODHD-APIs-Python-Financial-Library/blob/main/eodhd/apiclient.py#L715) in `apiclient.get_list_of_tickers` suggests that we should have the list of active tickers returned. However, the function returns the delisted tickers by default.

**Comment by Nawado** [comment]
Hello. We made changes in version 1.0.29, now it works correctly

**Comment by Comitica** [comment]
Great, thank you for the quick turnaround!

**Comment by Comitica** [comment]
Code matches expected behaviour
