### ISSUE TITLE
ModuleNotFoundError: No module named 'eodhd.APIs'

### ISSUE THREAD

**Issue by posidonius** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#5]
As per documentation:

`from eodhd import APIClient`

results in this error:

`ModuleNotFoundError: No module named 'eodhd.APIs'`

Somehow it is not recognizing the `APIs` submodule.

**Comment by Nawado** [comment]
Hi. Can you please tell me what version of the library you are using? You can find out if you enter pip freeze into the console.

And it would also help me solve the problem if I find out how you installed the library? Via pip or from github?

**Comment by posidonius** [comment]
Thanks for the response! I am using the most recent version  `eodhd-1.0.11`. I installed it using pip and have it installed in a pipenv virtual environment.

**Comment by Nawado** [comment]
Please try to upgrade version to 1.0.12. With new version this should work

**Comment by posidonius** [comment]
Great, that patch resolves the error. Thank you!

Just FYI, this package's dependencies are incompatible with the `eodhdc` library and both cannot be installed in the same project.
