### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by Sinansi** [EodHistoricalData/EODHD-APIs-Python-Financial-Library#6]
Does this library use exception handling?
I am using this library in PyCharm and it keep crashing it.
It crashes PyCharm whenever I enter any query that does not get processed by EODHD server.

For example, the following crashes PyCharm cause end date is invalid.
resp = api.get_historical_data("MSFT.US", "1m", "2023-01-01 23:56:00", "2023-02-30 23:59:00")

The following also crashes PyCharm cause it exceed the 120 days limit.
resp = api.get_historical_data("MSFT.US", "1m", "2022-01-30 23:56:00", "2023-01-30 23:59:00")

Any query that does not get processed by your server crashes PyCharm.

**Comment by deios0** [comment]
Hello, I do not think that it's a good position for PyCharm to crash on any 'unhandled' or 'incorrect' reply, I do belive you should have to ask guys from JetBrains why it happens. As I see you do request the data in datetime, but our documentation provides timestamps for intraday data.

**Comment by Sinansi** [comment]
I see the exception handling uses sys.exit(), that's why PyCharm keep shutting down every time a query does not get processed. It shutdown the interpreter.

Can I make suggestion?

Instead of shutting down the interpreter, when an invalid date is entered, perhaps the API can automatically find the nearest valid date? For example, if the last date input is February 30, the API can adjust it to February 28.

Another option, is to allow the end user to retrieve all valid dates on the server for a given stock, before sending the complete query.

**Comment by Sinansi** [comment]
All good. I made some changes and its working fine now. 
Thank you.

**Comment by deios0** [comment]
Thank you for the feedback!
